name: Java CI with Gradle

concurrency:
  group: "build-1.21"
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.20.6-build-${{ github.run_number }}"
          prerelease: false
          title: "1.20.6 Build ${{ github.run_number }}"
          files: |
            ./build/libs/*.jar
